replicaCount: 1
revisionHistoryLimit: 1

image:
  registry: herbrandson
  name: skooner
  tag: latest
  pullPolicy: Always

resources: {}

# If true will create skooner-sa and associate with cluster-admin role. Secret can be used for auth page with:
# kubectl describe secret skooner-sa-token-xxxxx
createServiceAccount: true

extraEnv: {}

service:
  httpPort: 4654

ingress:
  enabled: false
#  ingressClassName: nginx
  ## Kubernetes Dashboard Ingress annotations
  annotations: {}
  hosts:
    - host: www.example.com
      paths: [ "/" ]
  tls:
    - hosts:
        - "www.example.com"
    # secretName: tlsSecret

secondIngress:
  enabled: false
#  ingressClassName: nginx
  ## Kubernetes Dashboard Ingress annotations
  annotations: {}
  hosts:
    - host: www.example.com
      paths: [ "/" ]
  tls:
    - hosts:
        - "www.example.com"

affinity: {}

livenessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 6

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 4
  successThreshold: 1
  failureThreshold: 3

lifecycle: {}

podAnnotations: {}

nodeSelector: {}


