replicas: 1

# port where server is exposed
service:
  port: 4000

# name of the cluster to use in the generated kubeconfig file
clusterName: "verygoodcluster"

# full address of the control plane to use in the generated kubeconfig file
controlPlaneAddress: "https://kubernetes.example.com:8443"

# password used by basic auth (username is `admin`)
basicAuthPassword: "someverysecuredpassword"


podSecurityContext:
  fsGroup: 0

securityContext:
  runAsNonRoot: false
  runAsUser: 0

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - www.example.com
  tls:
    - hosts:
        - "www.example.com"

resources: {}

affinity: {}


